---
version: '3'

services:
  nct:
    build:
      context: v2
      dockerfile: Dockerfile
      args:
        COMMAND: ${COMMAND}
        GIT_VER: ${GIT_VER}
    image: ${CONTAINER_REGISTRY}/devops/nct:${GIT_VER:-latest}